/*
import React, { useEffect, useState, useContext } from 'react'
import { UserContext } from '../../App'
import { Switch } from 'react-router-dom'
import back2 from '../../back2.jpg'
import '../../App.css'
import M from 'materialize-css'


const AboutUs = () => {

  return (
    <div>
      <div className="about" style={{ backgroundImage: `url(${back2})` }}>
        <h1 style={{ fontSize: "68px" }}>About Us</h1>
      </div>
      <div className="about1">

        <p style={{ fontSize: "18px", fontFamily: "'Roboto', sans-serif" }}>Today, solid waste segregation is the biggest challenge faced by
        urban areas and metropolitan cities across the world. Especially, in a country like India which
        has weak environmental regulations, the situation is becoming worse. Satyamev Jayate,
        the popular TV talk show hosted by Aamir Khan highlighted the seriousness of this issue
        recently. According to a report from Delhi Development Authority, the city of Delhi alone
        produces 25,000 tons of waste every day.  This waste is dumped in the various locations
  around the city like Ghazipur, Okhla and Balsawa.<br />It is also shown inOscar wining movie
  ‘Slumdog Millionaire’. There was a mountain of garbage handled by several bulldozers and
  other bulky backhoe loaders and track excavators. Amidst this pile of waste, numerous rag
  pickers were waiting for new trucks of garbage, while some of them were engaged in
  segregation. Most of them were young kids aged 13-18 years. This is the place where poorest
   of the poor face the challenges of toxicity, health hazards and total quality of life
   because of the waste generated by us. Is there any solution to this grave problem?</p>
        <h1 style={{ color: "green", fontsize: "56px" }}>Here We Offer Door to Door Collection of Waste</h1>
        <p style={{ fontsize: "18px", fontFamily: "'Roboto', sans-serif " }}> Waste Elite is one of the leading provider of eco-friendly and
        dependable Door-to-Door collection services to households all across Delhi/NCR. We believe in
        reaching out at the grass-root levels to tackle the problems of waste and have developed
        superior Door-to-Door waste collection services to provide ease and convenience to our
        customers.

 <br /> We have the expertise to provide municipal bodies as well as the individuals households
  / societies / townships with much needed waste management services in terms of Door-to-Door
  collection, transportation and waste treatment. Our friendly waste collectors to whom we
  proudly refer to as ‘Health Officers’, reach your door step each day without fail to collect
  your waste and give you a clean experience.

 <br /> It’s not just your daily kitchen waste, but we also help you to get rid of your
  household, horticultural, construction generated waste in the most eco-friendly manner.</p>

      </div>
      <div style={{ marginBottom: "145px" }}>
        <img src={process.env.PUBLIC_URL + "/images/intro.png"} className="img-fluid" alt="introduction" />
      </div>
      <div className="row">
        <div className="col-lg-4 col-xl-4">
          <img alt="about" src={process.env.PUBLIC_URL + "/images/about2.jpg"} className="img-fluid" />
        </div>
        <div className="col-lg-4 col-xl-4"><img alt="about" src={process.env.PUBLIC_URL + "/images/abou3.jpg"} className="img-fluid" /></div>
        <div className="col-lg-4 col-xl-4"><img alt="about" src={process.env.PUBLIC_URL + "/images/about4.png"} className="img-fluid" /></div>


      </div>

      <div style={{ backgroundColor: "#1b5e20", paddingTop: "20px", marginBottom: "30px" }}>
        <h1 style={{ textAlign: "center", color: "white", marginTop: "20px" }}>Testinomials</h1>
        <div style={{ display: "flex", marginTop: "40px", marginRight: "20px", marginBottom: "20px", marginLeft: "20px" }}>
          <div className="card" style={{ marginRight: "20px", padding: "15px", color: "green", textAlign: "center" }}>
            <p>Waste Elite has been collecting waste from our organization for the last few
            years. They are the professional and credible waste management company in the NCR
            region based in Noida. Their process includes collection, segregation and
            transportation of wastes to the Recycling plant. I highly recommend them to any
            organization or housing group looking for waste management services.

     </p>
            <p className="author"><strong>- Ankita pal</strong></p>
          </div>
          <div className="card" style={{ marginRight: "20px", padding: "15px", color: "green", textAlign: "center" }}>
            <p>Trisha has been taking services of  Waste Elite since September 2008 and
            we are very satisfied with them .The best part about Waste Elite is that their 100%
            eco-friendly practices while dealing with scrap and other daily waste. With the
            realization within the IT industry to employ Green technologies be it electronic
            waste, scrap and daily wastage companies like Eco wise play a critical role in
            ensuring that government and global standards are met and the ecological balance
            is efficiently maintained.


</p>
            <p className="author"><strong>Ajit Singh</strong></p>
          </div>
          <div className="card" style={{ padding: "15px", color: "green", textAlign: "center" }}>
            <p>Waste Elite is a private company engaged in waste management services in
            the NCR. Eco Wise is providing yeoman’s services to the Noida. It has pioneered
            the expertise of converting the garbage into vermicompost and hygienically
            segregating the other waste material. Their unstinted efforts of making the
            environment clean and hygienically safe are indeed valuable. Eco Wise has been
            associated with Eldeco for over four years and we appreciate the good work being
            done and wish them great success in their Endeavour to improve the environment
            and promote greening of the area.

</p>
            <p className="author"><strong>- Nancy Katariya</strong></p>
          </div>
        </div><br />
      </div>

    </div>


  );


}
export default AboutUs
*/

import React from 'react'
import back2 from '../../back2.jpg'
import '../../App.css'

const AboutUs = () => {

  return (
    <div>
      <div className="about" style={{ backgroundImage: `url(${back2})` }}>
        <h1 style={{ fontSize: "68px" }}>About Us</h1>
      </div>

      <div className="about1">
        <p style={{ fontSize: "18px", fontFamily: "'Roboto', sans-serif" }}>
          Today, solid waste segregation is the biggest challenge faced by
          urban areas and metropolitan cities across the world. Especially, in a country like India which
          has weak environmental regulations, the situation is becoming worse. Satyamev Jayate,
          the popular TV talk show hosted by Aamir Khan highlighted the seriousness of this issue
          recently. According to a report from Delhi Development Authority, the city of Delhi alone
          produces 25,000 tons of waste every day. This waste is dumped in the various locations
          around the city like Ghazipur, Okhla and Balsawa.<br /><br />
          Amidst these piles of waste, numerous rag pickers including young children are exposed to
          severe health hazards. This raises a serious question — *Is there any sustainable solution?*
        </p>

        <h1 style={{ color: "green", fontSize: "36px", marginTop: "25px" }}>
          Here We Offer Door to Door Collection of Waste
        </h1>

        <p style={{ fontSize: "18px", fontFamily: "'Roboto', sans-serif" }}>
          Waste Elite is one of the leading providers of eco-friendly and dependable
          Door-to-Door waste collection services across Delhi/NCR. We reach the grassroots level to
          tackle waste problems and offer complete waste management solutions including collection,
          transportation, and treatment.<br /><br />
          Our waste collectors, whom we proudly refer to as ‘Health Officers’, reach your doorstep
          every day to collect waste and ensure a clean living environment.<br /><br />
          We also provide solutions for household waste, horticulture waste, and construction waste in
          the most environment-friendly manner.
        </p>
      </div>

      <div style={{ marginBottom: "145px" }}>
        <img src={process.env.PUBLIC_URL + "/images/intro.png"} className="img-fluid" alt="introduction" />
      </div>

      <div className="row" style={{ marginBottom: "40px" }}>
        <div className="col-lg-4 col-xl-4">
          <img alt="about" src={process.env.PUBLIC_URL + "/images/about2.jpg"} className="img-fluid" />
        </div>
        <div className="col-lg-4 col-xl-4">
          <img alt="about" src={process.env.PUBLIC_URL + "/images/abou3.jpg"} className="img-fluid" />
        </div>
        <div className="col-lg-4 col-xl-4">
          <img alt="about" src={process.env.PUBLIC_URL + "/images/about4.png"} className="img-fluid" />
        </div>
      </div>
    </div>
  );
}

export default AboutUs;

